CREATE SEQUENCE IF NOT EXISTS USER_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS BOOKING_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS INTERVIEWER_SLOT_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS CANDIDATE_SLOT_SEQUENCE;
CREATE INDEX IF NOT EXISTS idx_users_email ON USERS (EMAIL);
CREATE INDEX IF NOT EXISTS idx_users_role ON USERS (ROLE);
CREATE INDEX IF NOT EXISTS idx_cand_slot_date ON CANDIDATE_TIME_SLOT (DATE);
CREATE INDEX IF NOT EXISTS idx_interv_slot_weeknum ON INTERVIEWER_TIME_SLOT (WEEK_NUM);
-- CREATE INDEX on BOOKING(CANDIDATE_EMAIL);