CREATE SEQUENCE IF NOT EXISTS USER_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS BOOKING_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS INTERVIEWER_SLOT_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS CANDIDATE_SLOT_SEQUENCE;